name: Anchor Allocation Fetcher
on:
    workflow_dispatch:

jobs:
    send_anchor:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                repository: ${{ secrets.REPO_NAME }}
                token: ${{ secrets.GHPAT }}
            - name: Cache npm dependencies
              uses: actions/cache@v4
              with:
                path: '~/.npm'
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                                ${{ runner.os }}-node-
            - name: Install npm dependencies
              run: npm install
            - name: Run Update Script
              run: node bot.js pollanchor
              env:
                COMMONCR: ${{ secrets.COMCR }}